script

diff --git a/scripts/lab b/scripts/lab
--- a/scripts/lab
+++ b/scripts/lab
@@ -82,7 +82,7 @@ lab_scan_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--all, -a"
-    printf "    Target all machines\n"
+    printf "    Target all machines (Labs)\n"
     echo
 
     # :flag.usage
@@ -142,6 +142,21 @@ lab_exec_usage() {
     printf "%s\n" "Options:"
 
     # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--all, -a"
+    printf "    Target all machines (Labs)\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--output, -o"
+    printf "    Save the output of executed scripts\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--mask, -m"
+    printf "    Sets a custom mask, default 500\n"
+    echo
+
     # :flag.usage
     printf "  %s\n" "--script-file, -s FILEPATH"
     printf "    Allows to pass as script file to the remote machine\n"
@@ -207,7 +222,7 @@ lab_wake_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--all, -a"
-    printf "    Target all machines\n"
+    printf "    Target all machines (Labs)\n"
     echo
 
     # :flag.usage
@@ -263,7 +278,7 @@ lab_shutdown_usage() {
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--all, -a"
-    printf "    Target all machines\n"
+    printf "    Target all machines (Labs)\n"
     echo
 
     # :flag.usage
@@ -375,7 +390,7 @@ lab_scan_command() {
           done < $flag_file
       else
 
-          echo "No existe"
+          echo "File $flag_file does not exist"
           exit 1
 
       fi
@@ -433,7 +448,7 @@ lab_scan_command() {
 
       if [[ $flag_users ]]; then
 
-          if echo $status | grep -q 'DOWN'; then break;
+          if echo $status | grep -q 'DOWN'; then continue;
           else
 
               ssh_output=$(ssh -qt -o ConnectTimeout=2 -o StrictHostKeyChecking=no $account@$addr "who | cut -f1 -d' ' | sort -u")
@@ -455,6 +470,120 @@ lab_exec_command() {
   # echo "# you can edit it freely and regenerate (it will not be overwritten)"
   # inspect_args
 
+  # ----- CONFIG ---------
+  account="a798095"
+  # ----- FLAGS ----------
+  flag_all=${args[--all]}
+  flag_mask=${args[--mask]}
+  flag_output=${args[--output]}
+  flag_script=${args[--script-file]}
+  flag_targets=${args[--flood]}
+  # ----- ARGS -----------
+  hostname=${args[hostname]}
+  command=${args[command]}
+  # ----- Global ---------
+  target_list=()  # Lista de direcciones ip
+  # ----------------------
+
+  # Comprueba la existencia de la carpeta output
+  if [[ $flag_output ]]; then
+      if [ -d "output" ]; then
+          echo "The output folder exists, deleting its content..."
+          rm -rf output
+      else
+          echo "The output folder does not exist, creating an empty folder..."
+          mkdir output
+      fi
+  fi
+
+  # Comprueba que el script a ejecutar exista
+
+  if ! [ -f $flag_script ]; then
+      echo "File $flag_script does not exist"
+      exit 1
+  fi
+
+  # Crea una lista de ips objetivo
+  if [[ $flag_targets ]]; then
+      if [ -f $flag_targets ]; then
+          while read -r -d $'\n' linea; do
+              target_list+=("$linea")
+          done < $flag_targets
+      else
+
+          echo "File $flag_targets does not exist"
+          exit 1
+
+      fi
+  else
+      if [[ $flag_all ]]; then
+          # Rango de ips del lab102
+          for i in {191..210}; do
+              target_list+=("155.210.154.${i}")
+          done
+      else
+
+          target_list=$hostname
+      fi
+  fi
+
+  exec_remote () {
+      local addr=$1
+      local command=$2
+
+      if [[ $flag_output ]]; then
+          ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no ${account}@${addr} ${command} >> "output/$addr"
+      else
+
+          ssh -o ConnectTimeout=2 -o StrictHostKeyChecking=no ${account}@${addr} ${command}
+      fi
+
+      if [ $? -ne 0 ]; then
+          echo "Failed to execute the command on the remote server: $addr"
+      fi
+  }
+
+  apply_mask () {
+      local addr=$1
+      local filename=$2
+      if [[ $mask ]]; then
+          exec_remote $addr "chmod ${mask} ${filename}"
+      else
+          exec_remote $addr "chmod 700 ${filename}"
+      fi
+  }
+
+  # ----------------------------------------
+  #               EXECUTING
+
+  # ----------------------------------------
+
+  for addr in "${target_list[@]}"; do
+      if ! ping -c 1 -W 2 $addr >/dev/null 2>&1; then
+          echo "can't connect to: $addr"
+          continue
+      fi
+
+      if [[ $flag_script ]]; then
+          if scp ${flag_script} ${account}@${addr}:/home/${account}/lab_${flag_script} >/dev/null 2>&1; then
+              apply_mask ${addr} "lab_${flag_script}"
+              exec_remote ${addr} "./lab_${flag_script}"
+
+          elif scp ${flag_script} ${account}@${addr}:/home/${account}/lab_${flag_script} >/dev/null 2>&1; then
+              apply_mask ${addr} "lab_${flag_script}"
+              exec_remote ${addr} "./lab_${flag_script}"
+
+          else
+
+              echo "can't upload the script to: $addr"
+              continue
+          fi
+      else
+
+          exec_remote ${addr} ${command}
+      fi
+
+  done
 }
 
 # :command.function
@@ -486,7 +615,7 @@ lab_wake_command() {
           done < $flag_file
       else
 
-          echo "No existe"
+          echo "File $flag_file does not exist"
           exit 1
 
       fi
@@ -552,8 +681,9 @@ lab_shutdown_command() {
           done < $flag_file
       else
 
-          echo "No existe"
+          echo "File $flag_file does not exist"
           exit 1
+
       fi
   else
       if [[ $flag_all ]]; then
@@ -585,7 +715,7 @@ lab_shutdown_command() {
       # Prueba de conexion con el target
       if ! ping -c 1 -W 2 $addr >/dev/null 2>&1; then
           echo "can't connect to: $addr"
-          break
+          continue
       fi
       set +x
       # comprobar el numero de usuarios conectados a la maquina
@@ -594,7 +724,7 @@ lab_shutdown_command() {
 
       if [ $num_users -gt 1 ]; then
           echo "La maquina esta siendo usada por mas de un usuario"
-          break
+          continue
       fi
 
       # obtiene las maquinas virtuales que se estan ejecutando en la maquina $addr
@@ -603,10 +733,10 @@ lab_shutdown_command() {
       # comprueba si hay maquinas virtuales en ejecucion
       if [ $vm_running -eq 1 ]; then
           echo "Hay $vm_running maquina virtual ejecutandose"
-          break
+          continue
       elif [ $vm_running -gt 1 ]; then
           echo "Hay $vm_running maquinas virtuales ejecutandose"
-          break
+          continue
       fi
 
       # # Busqueda del nombre del host
@@ -821,6 +951,30 @@ lab_exec_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --all | -a)
+
+        # :flag.case_no_arg
+        args['--all']=1
+        shift
+        ;;
+
+      # :flag.case
+      --output | -o)
+
+        # :flag.case_no_arg
+        args['--output']=1
+        shift
+        ;;
+
+      # :flag.case
+      --mask | -m)
+
+        # :flag.case_no_arg
+        args['--mask']=1
+        shift
+        ;;
+
       # :flag.case
       --script-file | -s)
 
